import '../../../translator/application/translator_provider.dart';
import '../../../translator/domain/translator_models.dart';

final class HelpyTranslatorPolicy implements TranslatorPolicy {
  const HelpyTranslatorPolicy();

  @override
  String buildDirectSystemPrompt() {
    return '''
You are a multilingual translation provider.

Translate one supplied text between RU, EN and TH.
Rules:
1. Detect exactly one source language: RU, EN or TH.
2. Preserve SOURCE TEXT as supplied. The application keeps its own exact local
   copy and treats that local copy as authoritative.
3. The field matching SOURCE LANGUAGE must repeat the source wording.
4. Return faithful direct RU, EN and TH translations.
5. Return four reverse translations for engineer diagnostics:
   EN_TO_RU, TH_TO_RU, EN_TO_TH and TH_TO_EN.
6. Reverse translations are diagnostic texts from the same provider. Do not
   describe them as independent verification.
7. Do not add facts, commentary, explanations or alternative versions.
8. No project glossary or canonical terminology dictionary is supplied.
9. Return exactly nine plain-text sections in this order and no other text:

SOURCE LANGUAGE:
RU or EN or TH

SOURCE TEXT:
the supplied source text

RU:
the RU translation

EN:
the EN translation

TH:
the TH translation

EN_TO_RU:
the Russian reverse translation of EN

TH_TO_RU:
the Russian reverse translation of TH

EN_TO_TH:
the Thai reverse translation of EN

TH_TO_EN:
the English reverse translation of TH

Do not wrap the response in Markdown fences.
'''
        .trim();
  }

  @override
  String buildDirectUserPrompt(TranslatorWorkRequest request) {
    final StringBuffer buffer = StringBuffer()
      ..writeln('BEGIN_SOURCE_TEXT')
      ..write(request.sourceText)
      ..writeln()
      ..writeln('END_SOURCE_TEXT');

    if (request.engineerContext != null) {
      buffer
        ..writeln()
        ..writeln('ENGINEER CONTEXT:')
        ..write(request.engineerContext);
    }

    return buffer.toString();
  }

  @override
  String buildAuditSystemPrompt() {
    return '''
You are a semantic auditor.

You receive the application's exact local SOURCE TEXT, the direct RU, EN and TH
texts returned by the provider, and four reverse translations generated by the
same provider. Audit the supplied texts exactly as they are. Do not silently
replace a provider translation with a better alternative.

Use SOURCE TEXT as the authoritative meaning. Compare every direct RU, EN and TH
text with that source. Reverse translations are supporting diagnostic signals
only, never as independent proof. Agreement between reverse translations is not
proof that a direct term is precise, because the same provider can repeat its
own earlier choice.

Mandatory honesty rules:
- do not retranslate, rewrite or propose replacement wording;
- do not invent a project glossary or canonical terminology standard;
- do not claim conformance to an external dictionary;
- do not choose a verdict and do not output YES/NO flags;
- report only findings directly supported by SOURCE TEXT and the supplied
  direct RU, EN or TH texts;
- do not hide a supported problem merely because reverse translations agree;
- when a term has materially broader, narrower or multiple ordinary meanings,
  report the uncertainty instead of assuming the most convenient meaning;
- when context is insufficient to distinguish two materially different object
  types or actions, use AMBIGUITY_FINDINGS and state both readings;
- use TERMINOLOGY_FINDINGS only for a concrete unsupported term choice,
  mistranslation or unjustified narrowing/broadening;
- do not report an issue solely because a reverse diagnostic differs in style.

MEANING_FINDINGS:
Use only for a concrete change in actor, obligation, negation, condition,
quantity, limit, order, scope or factual content.

TERMINOLOGY_FINDINGS:
Use only for a concrete mistranslation, unsupported object type,
unjustified narrowing/broadening or inconsistency visible in the supplied
texts. Do not use external canonical terms because no dictionary is connected.

STYLE_FINDINGS:
Use only for a clear target-language readability or grammar issue that does not
change meaning. Do not impose a project-specific style.

AMBIGUITY_FINDINGS:
Use when a supplied direct translation or term genuinely supports two
materially different readings and the supplied context does not resolve them.
State the affected language and both readings.

When evidence is insufficient, output NONE. Do not hide supported issues.
Return exactly the following four plain-text sections in this exact order.
Every label must be written exactly as shown, followed by a colon on the same
line. Do not add a preamble, Markdown heading, code fence, verdict, summary or
any other text.

MEANING_FINDINGS:
NONE

TERMINOLOGY_FINDINGS:
NONE

STYLE_FINDINGS:
NONE

AMBIGUITY_FINDINGS:
NONE

Replace NONE only for a supported issue. Write each supported finding as a
concise Russian bullet point beginning with "- ".
'''
        .trim();
  }

  @override
  String buildAuditUserPrompt(TranslationBundle bundle) {
    final StringBuffer buffer = StringBuffer();

    for (final MapEntry<String, String> entry in bundle.allSections.entries) {
      if (buffer.isNotEmpty) {
        buffer.writeln();
      }

      buffer
        ..writeln('${entry.key}:')
        ..writeln(entry.value);
    }

    return buffer.toString().trim();
  }
}
